export const baseUrl='http://localhost:7000/admin/api'

export const loginPost='/login'
export const getUsers='/getUsers'
export const blockUser='/blockUser'
export const deleteUser='/deleteUser'
export const addCategory='/addCategory'
export const getCategory='/getCategory'
export const editCategory='/editCategory'
export const deleteCat='/deleteCategory'
export const addBrand='/addBrand'
export const getBrand='getBrand'
export const editBrand='/editBrand'
export const deleteBrand='/deleteBrand'
export const addProduct='/addProducts'
export const getproducts='/getProducts'
export const editproduct='/editproduct'
export const deleteProducts='/deleteProduct'
