export const baseUrl='http://localhost:7000/api'

export const signUpPost='/signUp'
export const loginPost='/login'
export const getCategory='/getCategory'
export const getproducts='/getProducts'
export const addCartProducts='/addCartProducts'
export const addToCart='/addToCart'
export const cartGet='/getCart'
export const deleteAllCart='/deleteCart'
export const deleteItem='/deleteItem'
export const addQuantity='/addQuantity'
export const minusQuantity='/minusQuantity'